apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
  generation: 1
  labels:
    name: demo-csvparser01
    tier: test
  name: demo-csvparser01
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      name: demo-csvparser01
      tier: test
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: demo-csvparser01
        tier: test
    spec:
      containers:
      - image: ACCOUNT.dkr.ecr.ap-south-1.amazonaws.com/demo-nginx:v4.0
        imagePullPolicy: Always
        name: demo-csvparser01
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: secret01
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: demo-csvparser01
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: demo-csvparser01
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50
