apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:ap-south-1:ACCOUNT:certificate/ID"
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
    service.beta.kubernetes.io/aws-load-balancer-access-log-emit-interval: "5"
    service.beta.kubernetes.io/aws-load-balancer-access-log-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-access-log-s3-bucket-name: puc-demo-k8s-logs
    service.beta.kubernetes.io/aws-load-balancer-access-log-s3-bucket-prefix: csvparser-k8s-app
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
  name: demo-csvparser01
  namespace: default
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      name: http
    - port: 443
      targetPort: 80
      name: https
  selector:
    name: demo-csvparser01
