variables:
  CONTAINER_DEV_IMAGE: ACCOUNT.dkr.ecr.ap-south-1.amazonaws.com/demo-nginx:$CI_COMMIT_SHA
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://localhost:2375

stages:
  - build
  - deploy

services:
  - docker:dind

build:
  stage: build
  image: docker:stable
  script:
    - apk add --no-cache curl jq python py-pip
    - pip install awscli
    - $(aws ecr get-login --no-include-email --region ap-south-1)
    - docker build --pull -t $CONTAINER_DEV_IMAGE .
    - docker push $CONTAINER_DEV_IMAGE

deploy:
  stage: deploy
  image: alpine
  script:
    - apk add --no-cache curl
    - curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
    - chmod +x ./kubectl
    - mv ./kubectl /usr/local/bin/kubectl
    - kubectl config set-cluster pucdemo --server="$KUBE_URL" --insecure-skip-tls-verify=true
    - kubectl config set-credentials admin --username="$KUBE_USER" --password="$KUBE_PASSWORD"
    - kubectl config set-context default --cluster=pucdemo --user=admin
    - kubectl config use-context default
    - kubectl set image deployment/demo-csvparser01 demo-csvparser01=$CONTAINER_DEV_IMAGE -n default
    - echo "Image Updated."
